/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-02 05:27:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/board/../menu.jsp", Long.valueOf(1501649089145L));
    _jspx_dependants.put("jar:file:/C:/Users/kwi12/OneDrive/문서/GitHub/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1499738191727L));
    _jspx_dependants.put("jar:file:/C:/Users/kwi12/OneDrive/문서/GitHub/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-35\" data-genuitec-path=\"/FinalProject/WebContent/menu.jsp\">\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Hydrogen &mdash; A free HTML5 Template by FREEHTML5.CO</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"Free HTML5 Template by FREEHTML5.CO\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"free html5, free template, free bootstrap, html5, css3, mobile first, responsive\" />\r\n");
      out.write("<meta name=\"author\" content=\"FREEHTML5.CO\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("\tFREE HTML5 TEMPLATE \r\n");
      out.write("\tDESIGNED & DEVELOPED by FREEHTML5.CO\r\n");
      out.write("\t\t\r\n");
      out.write("\tWebsite: \t\thttp://freehtml5.co/\r\n");
      out.write("\tEmail: \t\t\tinfo@freehtml5.co\r\n");
      out.write("\tTwitter: \t\thttp://twitter.com/fh5co\r\n");
      out.write("\tFacebook: \t\thttps://www.facebook.com/fh5co\r\n");
      out.write("\r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\t -->\r\n");
      out.write("\r\n");
      out.write("<!-- Facebook and Twitter integration -->\r\n");
      out.write("<meta property=\"og:title\" content=\"\" />\r\n");
      out.write("<meta property=\"og:image\" content=\"\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"\" />\r\n");
      out.write("<meta property=\"og:site_name\" content=\"\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Webfonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("<!-- Salvattore -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/salvattore.css\">\r\n");
      out.write("<!-- Theme Style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("<!-- FOR IE9 below -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"50873\",secure:\"50882\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<style>\r\n");
      out.write("#linkGroup {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tright: 1%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#alarm-content {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\ttop: 15%;\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ///////////////////////DropDown/////////////////////////////////// */\r\n");
      out.write(".menu, .menu ul, .menu li, .menu a {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\twidth: 1130px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tbackground: #4c4e5a;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #4c4e5a 0%, #2c2d33 100%);\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #4c4e5a 0%, #2c2d33 100%);\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #4c4e5a 0%, #2c2d33 100%);\r\n");
      out.write("\tbackground: -ms-linear-gradient(top, #4c4e5a 0%, #2c2d33 100%);\r\n");
      out.write("\tbackground: linear-gradient(top, #4c4e5a 0%, #2c2d33 100%);\r\n");
      out.write("\t-webkit-border-radius: 5px;\r\n");
      out.write("\t-moz-border-radius: 5px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tpadding: 0px 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \t.menu ul { display: none; } */\r\n");
      out.write(".menu li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 0 14px;\r\n");
      out.write("\tmargin: 6px 0;\r\n");
      out.write("\tline-height: 28px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tborder-left: 1px solid #393942;\r\n");
      out.write("\tborder-right: 1px solid #4f5058;\r\n");
      out.write("\tfont-family: Helvetica, Arial, sans-serif;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #f3f3f3;\r\n");
      out.write("\ttext-shadow: 1px 1px 1px rgba(0, 0, 0, .6);\r\n");
      out.write("\t-webkit-transition: color .2s ease-in-out;\r\n");
      out.write("\t-moz-transition: color .2s ease-in-out;\r\n");
      out.write("\t-o-transition: color .2s ease-in-out;\r\n");
      out.write("\t-ms-transition: color .2s ease-in-out;\r\n");
      out.write("\ttransition: color .2s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li:first-child a {\r\n");
      out.write("\tborder-left: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li:last-child a {\r\n");
      out.write("\tborder-right: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li:hover>a {\r\n");
      out.write("\tcolor: #8fde62;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("\ttop: 40px;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tbackground: #1f2024;\r\n");
      out.write("\t-webkit-border-radius: 0 0 5px 5px;\r\n");
      out.write("\t-moz-border-radius: 0 0 5px 5px;\r\n");
      out.write("\tborder-radius: 0 0 5px 5px;\r\n");
      out.write("\t-webkit-transition: opacity .25s ease .1s;\r\n");
      out.write("\t-moz-transition: opacity .25s ease .1s;\r\n");
      out.write("\t-o-transition: opacity .25s ease .1s;\r\n");
      out.write("\t-ms-transition: opacity .25s ease .1s;\r\n");
      out.write("\ttransition: opacity .25s ease .1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li:hover>ul {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li {\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\t-webkit-transition: height .25s ease .1s;\r\n");
      out.write("\t-moz-transition: height .25s ease .1s;\r\n");
      out.write("\t-o-transition: height .25s ease .1s;\r\n");
      out.write("\t-ms-transition: height .25s ease .1s;\r\n");
      out.write("\ttransition: height .25s ease .1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li:hover>ul li {\r\n");
      out.write("\theight: 36px;\r\n");
      out.write("\toverflow: visible;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li a {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("\t/* \t    padding: 4px 0 4px 40px; */\r\n");
      out.write("\t/* \t    margin: 0; */\r\n");
      out.write("\r\n");
      out.write("\t/* \t    border: none; */\r\n");
      out.write("\t/* \t    border-bottom: 1px solid #353539; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \t.menu ul li:last-child a { border: none; } */\r\n");
      out.write("\r\n");
      out.write("/* //////////////////////////////////////////////////////////////// */\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction MessageList() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"getMessage.do\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t$('#messagetable tr:gt(0)').remove();\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\t\t$('#messagetable').append(\"<tr><td><a id='\" + data[i].no + \"'class='messageDetail' data-toggle='modal' data-target='#messageModal'>\"\r\n");
      out.write("\t\t\t\t\t\t+ data[i].title + \"</a></td><td>\"\r\n");
      out.write("\t\t\t\t\t\t+ data[i].receiver + \"</td></tr>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//메뉴페이지가 처음불러와질때 알림에 표시되는 읽지않은 메세지 숫자\r\n");
      out.write("\tfunction MessageNum() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"getMessageCount.do\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t$('#togglerNum').text(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t$(document).on('click', '.messageDetail', function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"messageDetail.do\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tno : $(this).attr('id')\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('#titleLabel').text(data.title);\r\n");
      out.write("\t\t\t\t$('#senderLabel').text(data.sender);\r\n");
      out.write("\t\t\t\t$('#contentLabel').text(data.content);\r\n");
      out.write("\t\t\t\tMessageList();\r\n");
      out.write("\t\t\t\tMessageNum();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\talert(\"실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tMessageNum();\r\n");
      out.write("\r\n");
      out.write("\t\t//인터벌로 3초마다 알림에 표시되는 읽지않은 메세지 숫자\r\n");
      out.write("\t\tsetInterval(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getMessageCount.do\",\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$('#togglerNum').text(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}, 3000)\r\n");
      out.write("\r\n");
      out.write("\t\t//알림 눌렀을때 읽지않은 메세지 제목과 보낸사람 표시\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#toggler\").click(function() {\r\n");
      out.write("\t\t\tvar a = $(\"#toggler\").offset();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar left = a.left - 150;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#alarm-content\").css({\r\n");
      out.write("\t\t\t\t\"left\" : left\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#alarm-content\").slideToggle(1000);\r\n");
      out.write("\t\t\tMessageList();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- \t알림띄울 내용 -->\r\n");
      out.write("\t<div id=\"alarm-content\" style=\"background: white; z-index: 9;\">\r\n");
      out.write("\t\t<table class=\"table\" id=\"messagetable\" style=\"\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>새로도착한 쪽지</th>\r\n");
      out.write("\t\t\t\t<th>보낸이</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- \t메뉴 -->\r\n");
      out.write("\t<div id=\"fh5co-offcanvass\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"fh5co-offcanvass-close js-fh5co-offcanvass-close\">Menu\r\n");
      out.write("\t\t\t<i class=\"icon-cross\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<h1 class=\"fh5co-logo\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">Hydrogen</a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"profile.do?id=kwi1222@naver.com\">프로필</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"authority.do\">권한 신청</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"authorityManagerPage.do\">권한 신청 매니저</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"selling.do\">판매관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"purchasing.do\">구매관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"cashPage.do\">캐시관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"cashManager.do\">캐시 매니저</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"message.do\">쪽지관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"customerCenterCall.do\">고객센터</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- \t메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 메세지 상세  Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"messageModal\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">상세내용</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<table id=\"messageDetail\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"80%\">제&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;목\r\n");
      out.write("\t\t\t\t\t\t\t\t: <label id=\"titleLabel\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" rowspan=\"2\" align=\"center\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"button\" id=\"messageDelete\" class=\"btn btn-sm btn-danger\">삭제</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"80%\">보낸사람 : <label id=\"senderLabel\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><textarea id=\"contentLabel\" rows=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcols=\"78\" readonly=\"readonly\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"fh5co-header\" role=\"banner\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"search.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t<select name=\"major\" id=\"categoryForSearch\">\r\n");
      out.write("\t\t\t\t\t<option value=\"all\">카테고리</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select> <input type=\"text\" id=\"searchInput\" name=\"word\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div id=\"linkGroup\">\r\n");
      out.write("\t\t\t\t<a href='boardForm.do'>판매등록</a> <a href='loginprototype.jsp'>로그인</a>\r\n");
      out.write("\t\t\t\t<a href='#' id=\"toggler\">알림 <span class=\"badge\" id=\"togglerNum\"></span>\r\n");
      out.write("\t\t\t\t\t<a href='#'>마이페이지</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"fh5co-menu-btn js-fh5co-menu-btn\">Menu <i\r\n");
      out.write("\t\t\t\t\tclass=\"icon-menu\"></i></a> <a class=\"navbar-brand\" href=\"index.jsp\">Hydrogen</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- \t\t카테고리 메뉴                    -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"profile.do?id=a@naver.com\">디자인/그래픽</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#101\" class=\"documents\">캐리커쳐/인물/캐릭터/아이콘</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#102\" class=\"documents\">일러스트/초상화/스케치</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#103\" class=\"documents\">PPT\r\n");
      out.write("\t\t\t\t\t\t\t\t디자인/인포그래픽/캘리그라피/폰트/싸인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#104\" class=\"documents\">만화/웹툰</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#105\" class=\"documents\">사진/명함/이미지/포토샵/보정/합성</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#106\" class=\"documents\">블로그&카페 디자인/페이지/배경</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#107\" class=\"documents\">로고/심볼/마크/앰블럼/배너</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#108\" class=\"documents\">현수막/전단/간판/포스터</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#109\" class=\"documents\">도면/CAD/인테리어/3D</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#110\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">바이럴/마케팅/광고</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#201\" class=\"documents\">블로그/카페/체험단</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#202\" class=\"documents\">인스타그램/페이스북/카카오/트위터</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#203\" class=\"documents\">일반광고/옥외광고/광고대행/디스플레이\r\n");
      out.write("\t\t\t\t\t\t\t\t광고</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#204\" class=\"documents\">기획/컨설팅/분석/마케팅자료</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#205\" class=\"documents\">언론/기사/보도자료</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#206\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">문서/서식/레포트</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#301\" class=\"documents\">워드/타이핑/엑셀/통계</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#302\" class=\"documents\">창작/대본/시나리오/카피라이팅</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#303\" class=\"documents\">교정/교열/편집</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#304\" class=\"documents\">PPT제작/프리젠테이션</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#305\" class=\"documents\">글작성/리뷰/서평</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#306\" class=\"documents\">문서서식/자료/폼</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#307\" class=\"documents\">자기소개서/이력서</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#308\" class=\"documents\">사업계획서/제안서</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#309\" class=\"documents\">논문 컨설팅/보고서/리서치</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#310\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">컴퓨터/개발</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#401\" class=\"documents\">홈페이지/웹개발</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#402\" class=\"documents\">모바일/Web/App/어플</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#403\" class=\"documents\">수리/최적화/PC/서버/견적</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#404\" class=\"documents\">프로그래밍/프로그램/소스</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#405\" class=\"documents\">플래시/스크립트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#406\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">음악/영상</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#501\" class=\"documents\">영상제작/자막제작/편집</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#502\" class=\"documents\">작사/작곡/MR/음악편집/녹음</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#503\" class=\"documents\">나레이션/성우/목소리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#504\" class=\"documents\">음악레슨/노래/댄스</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#505\" class=\"documents\">인디음악/창작음악</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#506\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">생활/대행/상담</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#601\" class=\"documents\">고민상담/진로상담/취업상담/기타상담</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#602\" class=\"documents\">점/운세/사주/토정비결/궁합</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#603\" class=\"documents\">개인학습/강습</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#604\" class=\"documents\">이벤트/행사도우미/레크레이션</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#605\" class=\"documents\">미용/코디/스타일링/모델/피팅/건강</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#606\" class=\"documents\">하객대행/역할/MC/사회/연주/축가</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#607\" class=\"documents\">심부름/가사도우미/청소/이사</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#608\" class=\"documents\">단기알바/부업</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#609\" class=\"documents\">구매대행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#610\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">노하우/여행</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#701\" class=\"documents\">생활지식/비법/수리/노하우/팁</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#702\" class=\"documents\">투자/재테크</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#703\" class=\"documents\">자동차/연비/부품부속/튜닝</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#704\" class=\"documents\">요리/레시피</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#705\" class=\"documents\">국내여행/해외여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#706\" class=\"documents\">가이드/여행코스/여행지추천</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#707\" class=\"documents\">온라인게임</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#708\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">비즈니스/창업/사업</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#801\" class=\"documents\">사업계획/사업제안</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#802\" class=\"documents\">법인설립/사업자등록/통신판매</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#803\" class=\"documents\">리서치/컨설팅</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#804\" class=\"documents\">투자/금융/경매</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#805\" class=\"documents\">법무/인사/노동법/세무/회계</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#806\" class=\"documents\">창업상담/비즈니스 모델진단</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#807\" class=\"documents\">창업정보/창업자료/창업노하우</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#808\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">번역/외국어</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#901\" class=\"documents\">영어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#902\" class=\"documents\">일본어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#903\" class=\"documents\">중국어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#904\" class=\"documents\">러시아어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#905\" class=\"documents\">프랑스어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#906\" class=\"documents\">스페인어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#907\" class=\"documents\">독일어</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#908\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- END .header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<!-- \t<script src=\"js/jquery.min.js\"></script> -->\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<!-- Salvattore -->\r\n");
      out.write("\t<script src=\"js/salvattore.min.js\"></script>\r\n");
      out.write("\t<!-- Main JS -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://openapi.map.naver.com/openapi/v3/maps.js?clientId=A5owm24oXM2NprihulHy&submodules=geocoder\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"50873\",secure:\"50882\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#bckground{\r\n");
      out.write("width: 655px;\r\n");
      out.write("text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mapContent{\r\n");
      out.write("position: absolute;\r\n");
      out.write("display : none;\r\n");
      out.write("right: 15%;\r\n");
      out.write("top: 10%;\r\n");
      out.write("border: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    var map = new naver.maps.Map('map', {\r\n");
      out.write("    \tzoom: 12\r\n");
      out.write("    });\r\n");
      out.write("    var marker;\r\n");
      out.write("    var info_title = \"\"; //장소명\r\n");
      out.write("    var info_address = \"\";//도로명\r\n");
      out.write("    var info_address2 = \"\";//지번\r\n");
      out.write("    var latlng=\"\";//위도경도\r\n");
      out.write("    var information = \"\";//infowindow에 표시할 내용\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(document).on('click', '#mapSearch', function(){\r\n");
      out.write("    \tvar way = $('input[name=way]:checked').val();\r\n");
      out.write(" \t\tconsole.log(\"검색방식 1은 주소/ 2는 키워드 : \" + way);\r\n");
      out.write(" \t\t\r\n");
      out.write("    \tif($('#inputAddr').val() == \"\"){\r\n");
      out.write("\t  \t\t alert('검색어를 입력하세요');\r\n");
      out.write("\t  \t}else{\r\n");
      out.write("\t  \t\t\r\n");
      out.write("  \t\t \tif(way == 2){//키워드로 검색할 경우\r\n");
      out.write("  \t\t  \t\t \r\n");
      out.write("\t\t  \t\t $.ajax({\r\n");
      out.write("\t\t  \t\t\ttype : 'post',\r\n");
      out.write("\t\t  \t\t\turl : 'searchAddr.do',\r\n");
      out.write("\t\t  \t\t\tdata : {inputAddr:$('#inputAddr').val()},\r\n");
      out.write("\t\t  \t\t\tdataType : 'json',\r\n");
      out.write("\t\t  \t\t\tsuccess : function(data){\r\n");
      out.write("\t\t  \t\t\t\tconsole.log(data.items);\r\n");
      out.write("\t\t  \t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t//주소리스트\r\n");
      out.write("\t\t  \t\t\t\t$('#table tr:gt(0)').empty();\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t        $.each(data.items, function(index, value){\r\n");
      out.write("\t\t\t\t          \t$('#table tbody').append('<tr><td><input class=\"addrRadio\" type=\"radio\" name=\"address\" value=\"'+value.address+'\"><input type=\"hidden\" name=\"ttt\" value=\"'+value.title+'\">' + value.title +'</td><td>'+ value.address + '</td></tr>');\r\n");
      out.write("\t\t\t\t        });\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        map.destroy();\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t        map = new naver.maps.Map('map', {\r\n");
      out.write("\t  \t\t\t\t    \tzoom: 12\r\n");
      out.write("\t  \t\t\t\t    });\r\n");
      out.write("\t\t  \t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\tif(data.items[0] == null){\r\n");
      out.write("\t\t  \t\t\t\t\t$('#table tbody').append('<tr><th><h3>검색결과가 올바르지 않습니다. 검색방법이 맞는지 확인하세요</h3></th></tr>');\r\n");
      out.write("\t\t  \t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\tinfo_title = data.items[0].title;\r\n");
      out.write("\t\t  \t\t\t\t\tinfo_address = data.items[0].address;\r\n");
      out.write("\t\t  \t\t\t\t\tinfo_address2 = \"\";\r\n");
      out.write("\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t    \tnaver.maps.Service.geocode({address: info_address}, function(status, response) {\r\n");
      out.write("\t\t\t  \t\t\t    \tif (status !== naver.maps.Service.Status.OK) {\r\n");
      out.write("\t\t\t  \t\t\t    \t\treturn alert(info_address + '의 검색 결과가 없거나 기타 네트워크 에러');\r\n");
      out.write("\t\t\t  \t\t\t        }\r\n");
      out.write("\t\t\t  \t\t\t        var result = response.result;\r\n");
      out.write("\t\t\t  \t\t\t        // 검색 결과 갯수: result.total\r\n");
      out.write("\t\t\t  \t\t\t        // 첫번째 결과 결과 주소: result.items[0].address\r\n");
      out.write("\t\t\t  \t\t\t        // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x\r\n");
      out.write("\t\t  \t\t\t        \r\n");
      out.write("\t\t\t  \t\t\t        var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);\r\n");
      out.write("\t\t\t  \t\t\t        map.setCenter(myaddr); // 검색된 좌표로 지도 이동  \t\t\t          \r\n");
      out.write("\t\t  \t\t\t          \r\n");
      out.write("\t\t\t  \t\t\t        // 마커 표시\r\n");
      out.write("\t\t\t  \t\t\t        marker = new naver.maps.Marker({\r\n");
      out.write("\t\t\t  \t\t\t        \tposition: myaddr,\r\n");
      out.write("\t\t\t  \t\t\t            map: map\r\n");
      out.write("\t\t\t  \t\t\t            \r\n");
      out.write("\t\t\t  \t\t\t        });\r\n");
      out.write("\t\t  \t\t\t        \r\n");
      out.write("\t\t\t\t  \t\t\t    console.log(\"검색어로 검색할때 \" + response.result.item);\r\n");
      out.write("\t\t\t\t  \t\t\t    console.log(\"78번째줄\"+marker.position.x);\r\n");
      out.write("\t\t\t\t  \t\t\t    console.log(\"78번째줄\"+ result.items[0].address);\r\n");
      out.write("\t\t\t\t  \t\t\t    console.log(\"78번째줄\"+ result.items[0].title);\r\n");
      out.write("\t\t  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t  \t\t\t      \t//직접 지도에서 찍은 곳으로 마커 이동\r\n");
      out.write("\t\t\t\t\t  \t\t\tnaver.maps.Event.addListener(map, 'click', function(e) {\r\n");
      out.write("\t\t\t\t  \t\t\t\t\r\n");
      out.write("\t\t\t// \t\t  \t\t\t\tinfowindow.close();\r\n");
      out.write("\t\t\t\t\t\t\t\t    marker.setPosition(e.latlng);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t    console.log(e.latlng);\r\n");
      out.write("\t\t\t\t\t\t\t\t    searchCoordinateToAddress(e.latlng);\r\n");
      out.write("\t\t\t\t\t\t\t\t    info_title = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t  \t        \r\n");
      out.write("\t\t\t\t\t  \t        infowindow = new naver.maps.InfoWindow({\r\n");
      out.write("\t\t\t\t\t  \t        \t  content : \"<h5>\"+info_title+\"</h5><h6>\"+info_address+\"</h6>\"\r\n");
      out.write("\t\t\t\t\t  \t        });\r\n");
      out.write("\t\t\t\t\t  \t        \r\n");
      out.write("\t\t\t\t\t  \t        infowindow.open(map, marker);\r\n");
      out.write("\t\t\t\t\t  \t        lat = marker.position.y;\r\n");
      out.write("\t\t\t\t\t  \t        lng = marker.position.x;\r\n");
      out.write("\t\t\t\t\t  \t        \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  \t\t\t      \t});//geocode \r\n");
      out.write("\t\t  \t\t\t      \t\r\n");
      out.write("\t\t  \t\t\t\t}//검색 결과 else\r\n");
      out.write("\t\t  \t\t\t\t\r\n");
      out.write("\t\t  \t\t\t},\r\n");
      out.write("\t\t  \t\t\terror : function(jpXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t                  alert(textStatus);\r\n");
      out.write("\t\t                  alert(errorThrown);\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t  \t\t });//키워드 검색 ajax 끝\r\n");
      out.write("\t  \t\t \r\n");
      out.write("\t  \t\t \t $('#myModal').modal();\r\n");
      out.write("  \t \t\t}//키워드로 지도 찾는 경우 끝\r\n");
      out.write("  \t \t\t////////////////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("  \t \t\telse{//주소로 검색하는 경우(way==1)\r\n");
      out.write("  \t \t\t\t$('#table tr:gt(0)').empty();\r\n");
      out.write("\t\t\t\tinfo_address = $('#inputAddr').val();\r\n");
      out.write("\t\t\t\tinfo_address2 = \"\";\r\n");
      out.write("\t\t\t\tinfo_title = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t        map.destroy();\r\n");
      out.write("\t\t        map = new naver.maps.Map('map', {\r\n");
      out.write("\t\t\t\t    \tzoom: 12\r\n");
      out.write("\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t    naver.maps.Service.geocode({address: info_address}, function(status, response) {\r\n");
      out.write("\t\t\t    \tif (status !== naver.maps.Service.Status.OK) {\r\n");
      out.write("\t\t\t    \t\treturn alert('검색방법이 잘못 되었거나 기타 네트워크 에러');\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t        var result = response.result;\r\n");
      out.write("\t\t\t        // 검색 결과 갯수: result.total\r\n");
      out.write("\t\t\t        // 첫번째 결과 결과 주소: result.items[0].address\r\n");
      out.write("\t\t\t        // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t        var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);\r\n");
      out.write("\t\t\t        map.setCenter(myaddr); // 검색된 좌표로 지도 이동  \t\t\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t        //얘도 리스트 뿌릴수잇나\r\n");
      out.write("\t\t        \t$.each(result.items, function(index, value){\r\n");
      out.write("\t\t\t          \t$('#table tbody').append('<tr><td><input class=\"addrRadio\" type=\"radio\" name=\"address\" value=\"'+value.address+'\"><input type=\"hidden\" name=\"ttt\" value=\"'+value.title+'\"></td><td>'+ value.address + '</td></tr>');\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t          \r\n");
      out.write("\t\t\t        // 마커 표시\r\n");
      out.write("\t\t\t        marker = new naver.maps.Marker({\r\n");
      out.write("\t\t\t        \tposition: myaddr,\r\n");
      out.write("\t\t\t            map: map\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t        \tconsole.log(result);\r\n");
      out.write("\t\t      \t\tconsole.log(response.result.items);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t      \t\t//직접 지도에서 찍은 곳으로 마커 이동\r\n");
      out.write("\t\t\t\t\tnaver.maps.Event.addListener(map, 'click', function(e) {\r\n");
      out.write("\r\n");
      out.write("// \t\t  \t\t\t\tinfowindow.close();\r\n");
      out.write("\t\t    \t\t\tmarker.setPosition(e.latlng);\r\n");
      out.write("\t\t    \t\t\t\r\n");
      out.write("\t\t\t\t\t    searchCoordinateToAddress(e.latlng);\r\n");
      out.write("\t\t\t\t\t    info_title=\"\";\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("  \t        \r\n");
      out.write("\t\t  \t        //인포윈도우 오픈\r\n");
      out.write("\t\t  \t        infowindow = new naver.maps.InfoWindow({\r\n");
      out.write("\t\t  \t        \tcontent : result.userquery\r\n");
      out.write("\t\t  \t        });\r\n");
      out.write("\t\t  \t        console.log(info_title);\r\n");
      out.write("\t\t  \t        infowindow.open(map, marker);\r\n");
      out.write("\t\t  \t        lat = marker.position.y;\r\n");
      out.write("\t\t  \t        lng = marker.position.x;\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t      $('#myModal').modal();\r\n");
      out.write("\t\t      });//geocode 끝\r\n");
      out.write("\t\t    \r\n");
      out.write("  \t \t}//(way==1) else 끝\r\n");
      out.write("  \t \t\t\r\n");
      out.write("\t  \t}//검색어 입력 else\r\n");
      out.write("    })//검색방식 선택 했을경우 \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //라디오 선택\r\n");
      out.write("    $(document).on('click',\".addrRadio\",function(){\r\n");
      out.write("    \talert($(this).val());\r\n");
      out.write("    \t\r\n");
      out.write("\t\tvar myaddress = $(this).val();// 도로명 주소나 지번 주소만 가능 (건물명 불가!!!!)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t    naver.maps.Service.geocode({address: myaddress}, function(status, response) {\r\n");
      out.write("// \t    \tmap = new naver.maps.Map('map', {\r\n");
      out.write("// \t        \tzoom: 12\r\n");
      out.write("// \t        });\r\n");
      out.write("\t    \tif (status !== naver.maps.Service.Status.OK) {\r\n");
      out.write("\t    \t\treturn alert(myaddress + '의 검색 결과가 없거나 기타 네트워크 에러');\r\n");
      out.write("\t        }\r\n");
      out.write("\t        var result = response.result;\r\n");
      out.write("\t        console.log(result);\r\n");
      out.write("\t        // 검색 결과 갯수: result.total\r\n");
      out.write("\t        // 첫번째 결과 결과 주소: result.items[0].address\r\n");
      out.write("\t        // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x\r\n");
      out.write("\t        \r\n");
      out.write("\t        var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);\r\n");
      out.write("\t          \r\n");
      out.write("\t    \tmarker.setMap(null);\r\n");
      out.write("\t        // 마커 표시\r\n");
      out.write("\t        marker = new naver.maps.Marker({\r\n");
      out.write("\t        \tposition: myaddr,\r\n");
      out.write("\t            map: map\r\n");
      out.write("\t        });\r\n");
      out.write("\t        map.setCenter(myaddr); // 검색된 좌표로 지도 이동  \r\n");
      out.write("\t        console.log(result.items);\r\n");
      out.write("\t        info_address = myaddress;\r\n");
      out.write("\t        info_address2 = \"\";\r\n");
      out.write("\t        info_title = $('input[name=address]:checked + input').val()\r\n");
      out.write("\t        \r\n");
      out.write("\r\n");
      out.write("          // 인포윈도우 오픈\r\n");
      out.write("          infowindow = new naver.maps.InfoWindow({\r\n");
      out.write("        \t  content : \"<h5>\"+info_title+\"</h5><h6>\"+info_address+\"</h6>\"\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("          infowindow.open(map, marker);\r\n");
      out.write("\t     \r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("    });//라디오 선택 끝\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    //지점 찍었을 때 해당 좌표 -> 주소로 변환해주는 함수\r\n");
      out.write("    function searchCoordinateToAddress(latlng) {\r\n");
      out.write("\t\t \r\n");
      out.write("    \tvar tm128 = naver.maps.TransCoord.fromLatLngToTM128(latlng);//위경도를 tm128로 바꾸고\r\n");
      out.write("\r\n");
      out.write("    \tnaver.maps.Service.reverseGeocode({\r\n");
      out.write("\t        location: tm128,\r\n");
      out.write("\t        coordType: naver.maps.Service.CoordType.TM128\r\n");
      out.write("    \t}, function(status, response) {\r\n");
      out.write("    \t\r\n");
      out.write("\t        if (status === naver.maps.Service.Status.ERROR) {\r\n");
      out.write("\t            return alert('Something Wrong!');\r\n");
      out.write("\t        }\r\n");
      out.write("\t\r\n");
      out.write("\t        var items = response.result.items,\r\n");
      out.write("            htmlAddresses = [];\r\n");
      out.write("        \r\n");
      out.write("  \t          // 인포윈도우 오픈\r\n");
      out.write("  \t        infowindow = new naver.maps.InfoWindow({\r\n");
      out.write("  \t        \tcontent : \"<h6>\" + items[0].address+\"</h6><h6>\"+items[1].address+\"</h6>\"\r\n");
      out.write("  \t        });\r\n");
      out.write("  \t          \r\n");
      out.write("  \t        infowindow.open(map, marker);\r\n");
      out.write("  \t        info_address = items[0].address;\r\n");
      out.write("  \t        info_address2 = items[1].address\r\n");
      out.write("    \t});\r\n");
      out.write("\t}//searchCoordinateToAddress 함수 끝\r\n");
      out.write("\t///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    //클릭하면 지도 검색한 주소 가지고 부모창으로 가기\r\n");
      out.write("    $(document).on('click', \"#submit\", function(){\r\n");
      out.write("    \tconsole.log('클릭');\r\n");
      out.write("    \t\r\n");
      out.write("    \t//infowindow에 있는 내용 담아두자\r\n");
      out.write("    \tvar addrResult = $('h6').text();\r\n");
      out.write("    \tconsole.log($('h6').text());\r\n");
      out.write("    \t\r\n");
      out.write("    \t//부모창 div에 넣기\r\n");
      out.write("    \t$('#addrResult').html(info_title +\"<br>\"+ info_address +\"<br>\"+info_address2);\r\n");
      out.write("    \t$('#hidn').val(info_address);\r\n");
      out.write("    \t$('#hidn2').val(info_address2);\r\n");
      out.write("    \t$('#hidn3').val(info_title);\r\n");
      out.write("    \t$('#hidn4').val(lat);\r\n");
      out.write("    \t$('#hidn5').val(lng);\r\n");
      out.write("    \tconsole.log($('#hidn').text());\r\n");
      out.write("    });//부모창에 주소 가져가기 끝\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("//가격 입력하기\r\n");
      out.write("\r\n");
      out.write("\t$(document).on('click', '.add', function(){\r\n");
      out.write("\t$('#tableOption').append(\r\n");
      out.write("\t'<tr>'+\r\n");
      out.write("\t'<td><input type=\"text\" name=\"option[]\"></td>'+\r\n");
      out.write("\t'<td><input type=\"text\" name=\"optionPrice[]\"></td>'+\r\n");
      out.write("\t'<td><button class=\"delete\">삭제</button></td>'+\r\n");
      out.write("\t'</tr>'\r\n");
      out.write("\t);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click', '.delete', function(){\r\n");
      out.write("\t$(this).parent().parent().remove();\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("   \t$('#go').click(function(){\r\n");
      out.write("   \t\t$('#detailInfo').submit(function(){\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   \t$(document).on('change','#major', function(){\r\n");
      out.write("   \t\t$.ajax({\r\n");
      out.write("   \t\t\turl:\"categoryLow.do\",\r\n");
      out.write("   \t\t\ttype:\"POST\",\r\n");
      out.write("   \t\t\tdata:{high_no:$(this).val()},\r\n");
      out.write("   \t\t\tdataType:\"json\",\r\n");
      out.write("   \t\t\tsuccess:function(data){\r\n");
      out.write("   \t\t\t\tconsole.log(data);\r\n");
      out.write("   \t\t\t\t$('#minor').empty();\r\n");
      out.write("   \t\t\t\t$.each(data, function(index, value){\r\n");
      out.write("\t   \t\t\t\t$('#minor').append(\r\n");
      out.write("\t   \t\t\t\t\t\t'<option value=\"'+value.no+'\">'+value.category_name+'</option>'\t\r\n");
      out.write("\t   \t\t\t\t);\r\n");
      out.write("   \t\t\t\t});\r\n");
      out.write("   \t\t\t},\r\n");
      out.write("   \t\t\terror:function(){\r\n");
      out.write("   \t\t\t\talert(\"실패\");\r\n");
      out.write("   \t\t\t}\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t});//카테고리 ajax 끝\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("});//document.ready\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-7\" data-genuitec-path=\"/FinalProject/WebContent/board/updateBoard.jsp\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t<div id=\"fh5co-main\"> -->\r\n");
      out.write("\t\t<div class=\"container\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-7\" data-genuitec-path=\"/FinalProject/WebContent/board/updateBoard.jsp\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t\t<h2>판매글 수정</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"fh5co-spacer fh5co-spacer-sm\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-pricing-table\" id=\"bckground\">\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"detailInfo\" action=\"updateBoard.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>카테고리 </th><th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"major\" id=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"minor\" id=\"minor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>소분류</option><option>대분류를 선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>글제목</th><th> <input type=\"text\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>등록 마감일</th><th> <input type=\"date\" name=\"end_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.end_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>인원 또는 건수</th><th> <input type=\"text\" name=\"quantity\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.quantity }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>장소 또는 지역</th><th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"way\" value=\"1\" checked=\"checked\">주소\r\n");
      out.write("          \t\t\t\t\t\t\t\t<input type=\"radio\" name=\"way\" value=\"2\"> 키워드<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputAddr\" name=\"inputAddr\" > \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-sm\"  id=\"mapSearch\">검색</button> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"addrResult\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"hidn\" name=\"info_address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"hidn2\" name=\"info_address2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.address2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"hidn3\" name=\"info_title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"hidn4\" name=\"lat\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.lat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"hidn5\" name=\"lng\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.lng}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>기본가격</th><th> <input type=\"text\" name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>옵션사항</th><th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table id=\"tableOption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>옵션종류</th><th>추가가격</th><th><input type=\"button\" class=\"add\" value=\"추가\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>썸네일</th><th> <input type=\"file\" name=\"files\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${files.file_name1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>상세내용</th><th> <textarea rows=\"10\" cols=\"10\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea> </th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr><th>상세 이미지 또는 동영상</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"files\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${files.file_name2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"files\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${files.file_name3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"files\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${files.file_name4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</th></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fh5co-spacer fh5co-spacer-sm\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-sm btn-primary\" id=\"go\" value=\"GO!\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">주소를 선택하거나 지도상에서 직접 찍은 후 확인을 눌러주세요</h4>\r\n");
      out.write("\r\n");
      out.write("        </div>  \r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <div id=\"map\" style=\"width:858px;height:400px;text-align: center;\"></div>\r\n");
      out.write("          <table id=\"table\">\r\n");
      out.write("\t\t\t<tr><th>명칭</th><th>주소</th></tr>\r\n");
      out.write("\t\t  </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" id=\"submit\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<!--   손연경 -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /board/../menu.jsp(401,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/board/../menu.jsp(401,5) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/../menu.jsp(401,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("high");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${high.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${high.category_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /board/updateBoard.jsp(375,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/board/updateBoard.jsp(375,10) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/updateBoard.jsp(375,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("high");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${high.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${high.category_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /board/updateBoard.jsp(392,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.title ne ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /board/updateBoard.jsp(396,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.address2 ne '' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mapinfo.address2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /board/updateBoard.jsp(414,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/board/updateBoard.jsp(414,11) '${board_optionList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${board_optionList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/updateBoard.jsp(414,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("board_option");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"option[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board_option.kind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"optionPrice[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board_option.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td><button class=\"delete\">삭제</button></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
