/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-07-31 07:49:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class authorityManager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/member/../miniProfile.jsp", Long.valueOf(1501480272293L));
    _jspx_dependants.put("/member/../menu.jsp", Long.valueOf(1501480272258L));
    _jspx_dependants.put("jar:file:/C:/Users/kwi12/OneDrive/문서/GitHub/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1499738191727L));
    _jspx_dependants.put("jar:file:/C:/Users/kwi12/OneDrive/문서/GitHub/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-35\" data-genuitec-path=\"/FinalProject/WebContent/menu.jsp\">\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> <html class=\"no-js\"> <!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>Hydrogen &mdash; A free HTML5 Template by FREEHTML5.CO</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Free HTML5 Template by FREEHTML5.CO\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"free html5, free template, free bootstrap, html5, css3, mobile first, responsive\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"FREEHTML5.CO\" />\r\n");
      out.write("\t\r\n");
      out.write("  <!-- \r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("\tFREE HTML5 TEMPLATE \r\n");
      out.write("\tDESIGNED & DEVELOPED by FREEHTML5.CO\r\n");
      out.write("\t\t\r\n");
      out.write("\tWebsite: \t\thttp://freehtml5.co/\r\n");
      out.write("\tEmail: \t\t\tinfo@freehtml5.co\r\n");
      out.write("\tTwitter: \t\thttp://twitter.com/fh5co\r\n");
      out.write("\tFacebook: \t\thttps://www.facebook.com/fh5co\r\n");
      out.write("\r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\t -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Facebook and Twitter integration -->\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:image\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:url\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:site_name\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:description\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Google Webfonts -->\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Animate.css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("\t<!-- Icomoon Icon Fonts-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\t<!-- Salvattore -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/salvattore.css\">\r\n");
      out.write("\t<!-- Theme Style -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t<!-- Modernizr JS -->\r\n");
      out.write("\t<script src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\t<!-- FOR IE9 below -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"50873\",secure:\"50882\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t#linkGroup{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tright: 1%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#alarm-content{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay : none;\r\n");
      out.write("\tright: 15%;\r\n");
      out.write("\ttop: 10%;\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* ///////////////////////DropDown/////////////////////////////////// */\r\n");
      out.write("\t.menu,\r\n");
      out.write("\t.menu ul,\r\n");
      out.write("\t.menu li,\r\n");
      out.write("\t.menu a {\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t    border: none;\r\n");
      out.write("\t    outline: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t.menu {\r\n");
      out.write("\t    height: 40px;\r\n");
      out.write("\t    width: 1130px;\r\n");
      out.write("\t \tmargin: 0px auto;\r\n");
      out.write("\t \t\r\n");
      out.write("\t    background: #4c4e5a;\r\n");
      out.write("\t    background: -webkit-linear-gradient(top, #4c4e5a 0%,#2c2d33 100%);\r\n");
      out.write("\t    background: -moz-linear-gradient(top, #4c4e5a 0%,#2c2d33 100%);\r\n");
      out.write("\t    background: -o-linear-gradient(top, #4c4e5a 0%,#2c2d33 100%);\r\n");
      out.write("\t    background: -ms-linear-gradient(top, #4c4e5a 0%,#2c2d33 100%);\r\n");
      out.write("\t    background: linear-gradient(top, #4c4e5a 0%,#2c2d33 100%);\r\n");
      out.write("\t \r\n");
      out.write("\t    -webkit-border-radius: 5px;\r\n");
      out.write("\t    -moz-border-radius: 5px;\r\n");
      out.write("\t    border-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t.menu li {\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    list-style: none;\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    height: 40px;\r\n");
      out.write("\t    padding:0px 6px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("/* \t.menu ul { display: none; } */\r\n");
      out.write("\t\r\n");
      out.write("\t.menu li a {\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    padding: 0 14px;\r\n");
      out.write("\t    margin: 6px 0;\r\n");
      out.write("\t    line-height: 28px;\r\n");
      out.write("\t    text-decoration: none;\r\n");
      out.write("\t \r\n");
      out.write("\t    border-left: 1px solid #393942;\r\n");
      out.write("\t    border-right: 1px solid #4f5058;\r\n");
      out.write("\t \r\n");
      out.write("\t    font-family: Helvetica, Arial, sans-serif;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    font-size: 13px;\r\n");
      out.write("\t \r\n");
      out.write("\t    color: #f3f3f3;\r\n");
      out.write("\t    text-shadow: 1px 1px 1px rgba(0,0,0,.6);\r\n");
      out.write("\t \r\n");
      out.write("\t    -webkit-transition: color .2s ease-in-out;\r\n");
      out.write("\t    -moz-transition: color .2s ease-in-out;\r\n");
      out.write("\t    -o-transition: color .2s ease-in-out;\r\n");
      out.write("\t    -ms-transition: color .2s ease-in-out;\r\n");
      out.write("\t    transition: color .2s ease-in-out;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t.menu li:first-child a { border-left: none; }\r\n");
      out.write("\t.menu li:last-child a{ border-right: none; }\r\n");
      out.write("\t \r\n");
      out.write("\t.menu li:hover > a { color: #8fde62; }\r\n");
      out.write("\t\r\n");
      out.write("\t.menu ul {\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    z-index:5;\r\n");
      out.write("\t    top: 40px;\r\n");
      out.write("\t    left: 0;\r\n");
      out.write("\t \r\n");
      out.write("\t    opacity: 0;\r\n");
      out.write("\t    background: #1f2024;\r\n");
      out.write("\t \r\n");
      out.write("\t    -webkit-border-radius: 0 0 5px 5px;\r\n");
      out.write("\t    -moz-border-radius: 0 0 5px 5px;\r\n");
      out.write("\t    border-radius: 0 0 5px 5px;\r\n");
      out.write("\t \r\n");
      out.write("\t    -webkit-transition: opacity .25s ease .1s;\r\n");
      out.write("\t    -moz-transition: opacity .25s ease .1s;\r\n");
      out.write("\t    -o-transition: opacity .25s ease .1s;\r\n");
      out.write("\t    -ms-transition: opacity .25s ease .1s;\r\n");
      out.write("\t    transition: opacity .25s ease .1s;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t.menu li:hover > ul { opacity: 1; }\r\n");
      out.write("\t \r\n");
      out.write("\t.menu ul li {\r\n");
      out.write("\t    height: 0;\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t \r\n");
      out.write("\t    -webkit-transition: height .25s ease .1s;\r\n");
      out.write("\t    -moz-transition: height .25s ease .1s;\r\n");
      out.write("\t    -o-transition: height .25s ease .1s;\r\n");
      out.write("\t    -ms-transition: height .25s ease .1s;\r\n");
      out.write("\t    transition: height .25s ease .1s;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t.menu li:hover > ul li {\r\n");
      out.write("\t    height: 36px;\r\n");
      out.write("\t    overflow: visible;\r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \t.menu ul li a { \r\n");
      out.write(" \t    width: 300px; \r\n");
      out.write(" \t    z-index: 5;\r\n");
      out.write("/* \t    padding: 4px 0 4px 40px; */\r\n");
      out.write("/* \t    margin: 0; */\r\n");
      out.write("\t \r\n");
      out.write("/* \t    border: none; */\r\n");
      out.write("/* \t    border-bottom: 1px solid #353539; */\r\n");
      out.write(" \t} \r\n");
      out.write("\t \r\n");
      out.write("/* \t.menu ul li:last-child a { border: none; } */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* //////////////////////////////////////////////////////////////// */\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-2.2.4.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\"#toggler\").click(function(){\r\n");
      out.write("    \t$( \"#alarm-content\" ).slideToggle(1000);\r\n");
      out.write("    });   \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \t알림띄울 내용 -->\r\n");
      out.write("<div id=\"alarm-content\">\r\n");
      out.write("<!-- \t\t<div class=\"col-md-4\"> -->\r\n");
      out.write("<!-- \t\t\t<div class=\"fh5co-pricing-table\"> -->\r\n");
      out.write("\t\t\t\t<table class=\"table\" style=\"background: white;\">\r\n");
      out.write("\t\t\t\t\t<tr><th>새로도착한 쪽지</th><th>보낸이</th></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>칼갈아드립니다</td><td>려차ㅑㅜㅎ 샣힏</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \t메뉴 -->\r\n");
      out.write("\t<div id=\"fh5co-offcanvass\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"fh5co-offcanvass-close js-fh5co-offcanvass-close\">Menu <i class=\"icon-cross\"></i> </a>\r\n");
      out.write("\t\t<h1 class=\"fh5co-logo\"><a class=\"navbar-brand\" href=\"index.jsp\">Hydrogen</a></h1>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"profile.do?id=kwi1222@naver.com\">프로필</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"detailOneBoard2.do?no=1\">글상세</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"authority.do\">권한 신청</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"authorityManagerPage.do\">권한 신청 매니저</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"selling.jsp\">판매관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"purchasing.jsp\">구매관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"cashPage.do\">캐시관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"cashManager.do\">캐시 매니저</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"message.do\">쪽지관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"customerCenterCall.do\">고객센터</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- \t메뉴 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<header id=\"fh5co-header\" role=\"banner\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<form action=\"search.do\" method=\"post\">\r\n");
      out.write("\t\t검색 <input type=\"text\" id=\"searchInput\" name=\"word\"> \r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div id=\"linkGroup\">\r\n");
      out.write("\t\t\t<a href='boardForm.do'>판매등록</a>\r\n");
      out.write("\t\t\t<a href='loginprototype.jsp'>로그인</a>\r\n");
      out.write("\t\t\t<a href='#' id=\"toggler\">알림</a>\r\n");
      out.write("\t\t\t<a href='#'>마이페이지</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"fh5co-menu-btn js-fh5co-menu-btn\">Menu <i class=\"icon-menu\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">Hydrogen</a>\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t카테고리 메뉴                    -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t    <li><a href=\"profile.do?id=a@naver.com\">디자인/그래픽</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#101\" class=\"documents\">캐리커쳐/인물/캐릭터/아이콘</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#102\" class=\"documents\">일러스트/초상화/스케치</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#103\" class=\"documents\">PPT 디자인/인포그래픽/캘리그라피/폰트/싸인</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#104\" class=\"documents\">만화/웹툰</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#105\" class=\"documents\">사진/명함/이미지/포토샵/보정/합성</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#106\" class=\"documents\">블로그&카페 디자인/페이지/배경</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#107\" class=\"documents\">로고/심볼/마크/앰블럼/배너</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#108\" class=\"documents\">현수막/전단/간판/포스터</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#109\" class=\"documents\">도면/CAD/인테리어/3D</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#110\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">바이럴/마케팅/광고</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#201\" class=\"documents\">블로그/카페/체험단</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#202\" class=\"documents\">인스타그램/페이스북/카카오/트위터</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#203\" class=\"documents\">일반광고/옥외광고/광고대행/디스플레이 광고</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#204\" class=\"documents\">기획/컨설팅/분석/마케팅자료</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#205\" class=\"documents\">언론/기사/보도자료</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#206\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">문서/서식/레포트</a>\r\n");
      out.write("\t\t\t\t        <ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#301\" class=\"documents\">워드/타이핑/엑셀/통계</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#302\" class=\"documents\">창작/대본/시나리오/카피라이팅</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#303\" class=\"documents\">교정/교열/편집</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#304\" class=\"documents\">PPT제작/프리젠테이션</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#305\" class=\"documents\">글작성/리뷰/서평</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#306\" class=\"documents\">문서서식/자료/폼</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#307\" class=\"documents\">자기소개서/이력서</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#308\" class=\"documents\">사업계획서/제안서</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#309\" class=\"documents\">논문 컨설팅/보고서/리서치</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#310\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">컴퓨터/개발</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#401\" class=\"documents\">홈페이지/웹개발</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#402\" class=\"documents\">모바일/Web/App/어플</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#403\" class=\"documents\">수리/최적화/PC/서버/견적</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#404\" class=\"documents\">프로그래밍/프로그램/소스</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#405\" class=\"documents\">플래시/스크립트</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#406\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">음악/영상</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#501\" class=\"documents\">영상제작/자막제작/편집</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#502\" class=\"documents\">작사/작곡/MR/음악편집/녹음</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#503\" class=\"documents\">나레이션/성우/목소리</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#504\" class=\"documents\">음악레슨/노래/댄스</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#505\" class=\"documents\">인디음악/창작음악</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#506\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">생활/대행/상담</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#601\" class=\"documents\">고민상담/진로상담/취업상담/기타상담</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#602\" class=\"documents\">점/운세/사주/토정비결/궁합</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#603\" class=\"documents\">개인학습/강습</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#604\" class=\"documents\">이벤트/행사도우미/레크레이션</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#605\" class=\"documents\">미용/코디/스타일링/모델/피팅/건강</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#606\" class=\"documents\">하객대행/역할/MC/사회/연주/축가</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#607\" class=\"documents\">심부름/가사도우미/청소/이사</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#608\" class=\"documents\">단기알바/부업</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#609\" class=\"documents\">구매대행</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#610\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">노하우/여행</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#701\" class=\"documents\">생활지식/비법/수리/노하우/팁</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#702\" class=\"documents\">투자/재테크</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#703\" class=\"documents\">자동차/연비/부품부속/튜닝</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#704\" class=\"documents\">요리/레시피</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#705\" class=\"documents\">국내여행/해외여행</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#706\" class=\"documents\">가이드/여행코스/여행지추천</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#707\" class=\"documents\">온라인게임</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#708\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">비즈니스/창업/사업</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#801\" class=\"documents\">사업계획/사업제안</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#802\" class=\"documents\">법인설립/사업자등록/통신판매</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#803\" class=\"documents\">리서치/컨설팅</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#804\" class=\"documents\">투자/금융/경매</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#805\" class=\"documents\">법무/인사/노동법/세무/회계</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#806\" class=\"documents\">창업상담/비즈니스 모델진단</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#807\" class=\"documents\">창업정보/창업자료/창업노하우</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#808\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"#\">번역/외국어</a>\r\n");
      out.write("\t\t\t\t    \t<ul>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#901\" class=\"documents\">영어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#902\" class=\"documents\">일본어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#903\" class=\"documents\">중국어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#904\" class=\"documents\">러시아어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#905\" class=\"documents\">프랑스어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#906\" class=\"documents\">스페인어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#907\" class=\"documents\">독일어</a></li>\r\n");
      out.write("\t\t\t\t    \t\t<li><a href=\"#908\" class=\"documents\">기타</a></li>\r\n");
      out.write("\t\t\t\t    \t</ul>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- END .header -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("<!-- \t<script src=\"js/jquery.min.js\"></script> -->\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<!-- Salvattore -->\r\n");
      out.write("\t<script src=\"js/salvattore.min.js\"></script>\r\n");
      out.write("\t<!-- Main JS -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#miniProfile{\r\n");
      out.write("\t\tborder:1px solid black;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop:37%;\r\n");
      out.write("\t\tleft:10%;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\twidth:200px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.miniImg{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 13%;\r\n");
      out.write("\t\ttop:30%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tz-index:4;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgSpace{\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"50873\",secure:\"50882\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-36\" data-genuitec-path=\"/FinalProject/WebContent/miniProfile.jsp\">\r\n");
      out.write("<div data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-36\" data-genuitec-path=\"/FinalProject/WebContent/miniProfile.jsp\">\r\n");
      out.write("<img src=\"images/img_1.jpg\" class=\"img-circle miniImg\">\r\n");
      out.write("<table id=\"miniProfile\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"imgSpace\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.nickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><label class=\"balance\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("</label>원</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=\"button\" value=\"충전\" class=\"btn btn-sm btn-info\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>나의 재능 : 0건</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>판매중인 재능 : 0건</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>거래중인 재능 : 0건</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>관심 재능 : 0건</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>쪽지 : 0건</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <script src=\"js/jquery.form.js\"></script> -->\r\n");
      out.write("<!-- <script src=\"js/jquery.MetaData.js\"></script> -->\r\n");
      out.write("<script src=\"js/jQuery.MultiFile.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.cycle2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\tfunction telentList(page){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"authorityManager.do\",\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tpage:page\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t$('#talentList tr:gt(1)').remove();\r\n");
      out.write("\t\t\t\t$.each(data.list, function(index, value){\r\n");
      out.write("\t\t\t\t\t$('#talentList').append(\r\n");
      out.write("\t\t\t\t\t\t\"<tr><td>\"+value.no+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\tvalue.id+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\tvalue.category_no+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\tvalue.date+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button value='\"+value.no+\"' class='btn-sm btn-info detailBtn'>상세보기</button></td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' value='\"+value.no+\"' class='btn btn-sm btn-info approvalBtn' >승인</button> / <button type='button' value='\"+value.no+\"' class='btn btn-sm btn-danger cancelBtn' >취소</button></td></tr>\"\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t\t$('#currentPage').val(data.page);\r\n");
      out.write("\t\t\t\t$('.prev').val(data.page==0?0:data.page-10);\r\n");
      out.write("\t\t\t\t$('.next').val(data.totalPage-10>data.page?data.page+10:data.page);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(){\r\n");
      out.write("\t\t\t\talert(\"실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttelentList(0);\r\n");
      out.write("\t\r\n");
      out.write("\t$('#btnDiv button').click(function(){\r\n");
      out.write("\t\ttelentList($(this).val());\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click','.approvalBtn', function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"authorityUpdate.do\",\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tno:$(this).val(),\r\n");
      out.write("\t\t\t\tstate:2\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\ttelentList(0);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(){\r\n");
      out.write("\t\t\t\talert(\"실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click','.cancelBtn', function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"authorityUpdate.do\",\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tno:$(this).val(),\r\n");
      out.write("\t\t\t\tstate:3\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\ttelentList(0);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(){\r\n");
      out.write("\t\t\t\talert(\"실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on('click', '.detailBtn', function(){\r\n");
      out.write("\r\n");
      out.write("\t\t$('#cycle-slideshow').empty();\r\n");
      out.write("\t\t$('#downloadList li').empty();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"authorityDetail.do\",\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdata:{no:$(this).val()},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(data.file1!=\"\"){\r\n");
      out.write("\t\t\t\t\t$('#cycle-slideshow').append('<img src=\"\" id=\"imageFile1\">');\r\n");
      out.write("\t\t\t\t\t$('#imageFile1').attr('src',\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("/\"+data.file1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#download1').html(\"<a href='download.do?no=\"+data.no+\"&name=\"+data.file1+\"'>\"+data.file1+\"</a>\");\r\n");
      out.write("\t\t\t\t\t$('#download2').html(\"첨부 파일 없음\");\r\n");
      out.write("\t\t\t\t\t$('#download3').html(\"첨부 파일 없음\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.file2!=\"\"){\r\n");
      out.write("\t\t\t\t\t$('#cycle-slideshow').append('<img src=\"\" id=\"imageFile2\">');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#imageFile2').attr('src',\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("/\"+data.file2);\r\n");
      out.write("\t\t\t\t\t$('#download2').html(\"<a href='download.do?no=\"+data.no+\"&name=\"+data.file2+\"'>\"+data.file2+\"</a>\");\r\n");
      out.write("\t\t\t\t\t$('#download3').html(\"첨부 파일 없음\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.file3!=\"\"){\r\n");
      out.write("\t\t\t\t\t$('#cycle-slideshow').append('<img src=\"\" id=\"imageFile3\">');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#imageFile3').attr('src',\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("/\"+data.file3);\r\n");
      out.write("\t\t\t\t\t$('#download3').html(\"<a href='download.do?no=\"+data.no+\"&name=\"+data.file3+\"'>\"+data.file3+\"</a>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#cycle-slideshow').cycle({\r\n");
      out.write("\t\t\t\t\tfx: 'fade',\r\n");
      out.write("\t\t\t\t\tspeed: 300,\r\n");
      out.write("\t\t\t\t\ttimeout:0,\r\n");
      out.write("\t\t\t\t\tnext:'#nextImg',\r\n");
      out.write("\t\t\t\t\tprev:'#prevImg'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#detailModal').modal('show');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(){\r\n");
      out.write("\t\t\t\talert(\"실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("// \t\t$('#imageFile1').attr('src', '");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("/')\r\n");
      out.write("\t\t\r\n");
      out.write("// \t\t$('#detailModal').modal('show');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"50873\",secure:\"50882\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-29\" data-genuitec-path=\"/FinalProject/WebContent/member/authorityManager.jsp\">\r\n");
      out.write("<style data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-29\" data-genuitec-path=\"/FinalProject/WebContent/member/authorityManager.jsp\">\r\n");
      out.write("\t#talentList{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\twidth: 750px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin:10px 0px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#talentTable{\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#talentList td{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn{\r\n");
      out.write("\t\tline-height:15px;\r\n");
      out.write("\t\tmargin: 10px 10px;\r\n");
      out.write("\t\tpadding: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-danger, .register{\r\n");
      out.write("\t\tmargin: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#btnDiv{\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-body{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cycle-pager{\r\n");
      out.write("\t\tfont-size: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\timg{\r\n");
      out.write("\t\twidth: 550px;\r\n");
      out.write("\t\theight: 600px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul{\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-md-8{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tleft: 10%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#btnDiv{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 95%;\r\n");
      out.write("\t\tleft: 55%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<input type=\"hidden\" id=\"currentPage\" value=\"\">\r\n");
      out.write("\t<div id=\"fh5co-main\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t\t<h2>권한 신청 매니저</h2>\r\n");
      out.write("\t\t\t\t\t<table id=\"talentList\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"7\">신청한 재능</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>재능</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>신청일시</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>첨부</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>비고</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"btnDiv\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-sm btn-info prev\" value=\"\">이전</button>&nbsp;&nbsp;&nbsp;&nbsp;<button class=\"btn-sm btn-info next\" value=\"\">다음</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 상세보기 Modal -->\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"modal fade\" id=\"detailModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t      <!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t      <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t          <h4 class=\"modal-title\">상세 보기</h4>\r\n");
      out.write("\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t        \t<div id=\"cycle-slideshow\" >\r\n");
      out.write("<!-- \t\t\t\t\t\t\t         \t<img src=\"images/img_1.jpg\" id=\"imageFile1\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t          \t<img src=\"images/img_1.jpg\" id=\"imageFile2\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t          \t<img src=\"images/img_1.jpg\" id=\"imageFile3\"> -->\r\n");
      out.write("\t\t\t\t\t\t          \t</div>\r\n");
      out.write("\t\t\t\t\t\t          \t<div id=\"nav\" class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t          \t\t<a id=\"prevImg\" href=\"#\">이전</a>\r\n");
      out.write("\t\t\t\t\t\t          \t\t<a id=\"nextImg\" href=\"#\">다음</a>\r\n");
      out.write("\t\t\t\t\t\t          \t</div>\r\n");
      out.write("\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t        \t<ul id=\"downloadList\">\r\n");
      out.write("\t\t\t\t\t\t        \t\t<li id=\"download1\"></li>\r\n");
      out.write("\t\t\t\t\t\t        \t\t<li id=\"download2\"></li>\r\n");
      out.write("\t\t\t\t\t\t        \t\t<li id=\"download3\"></li>\r\n");
      out.write("\t\t\t\t\t\t        \t</ul>\r\n");
      out.write("\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /member/../miniProfile.jsp(47,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.balance}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /member/../miniProfile.jsp(47,29) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /member/authorityManager.jsp(106,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/user/authority/\"+data.no+\"");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /member/authorityManager.jsp(116,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/user/authority/\"+data.no+\"");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /member/authorityManager.jsp(124,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/user/authority/\"+data.no+\"");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /member/authorityManager.jsp(144,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/user/authority/'+no+'");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }
}
